apiVersion: apps/v1
kind: Deployment
metadata:
  name: airport-server-deployment
  labels:
   app: airport-server
spec:
  replicas: 5
  selector:
   matchLabels:
    app: airport-server
  template:
    metadata:
      labels:
        app: airport-server
    spec:
      containers:
      - name: airport-server
        image: varunmachingal92/airports-node:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
---
kind: Service
apiVersion: v1
metadata:
  name: airport-server
spec:
  type: LoadBalancer
  selector:
   app: airport-server
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
    nodePort: 30045

