apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-deployment
  labels:
   app: node-server        
spec:
  replicas: 1
  selector:
   matchLabels:
    app: node-server        
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: varunmachingal92/node-server:v7
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: node-server
spec:
  type: NodePort
  selector:
   app: node-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30015

