kind: Service
apiVersion: v1
metadata:
  name: node-server
spec:
  type: LoadBalancer
  selector:
   app: node-server
   color: blue
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30015
