apiVersion: apps/v1
kind: Deployment
metadata:
  name: uinode-deployment-green
  labels:
    app: ui-node
    kube-monkey/enabled: "enabled"
    kube-monkey/identifier: "ui-node"
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"   
spec:
  replicas: 1
  selector:
   matchLabels:
    app: ui-node        
  template:
    metadata:
      labels:
        app: ui-node
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "ui-node"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
        color: green
    spec:
      containers:
      - name: ui-node
        image: varunmachingal92/ui-node-green:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001

