apiVersion: apps/v1
kind: Deployment
metadata:
  name: uinode-deployment
  labels:
   app: ui-node    
spec:
  replicas: 3
  selector:
   matchLabels:
    app: ui-node        
  template:
    metadata:
      labels:
        app: ui-node
        kube-monkey/enabled: enabled
        kube-monkey/identifier: monkey-victim
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
    spec:
      containers:
      - name: ui-node
        image: varunmachingal92/ui-node-green:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
---
kind: Service
apiVersion: v1
metadata:
  name: ui-node
spec:
  type: NodePort
  selector:
   app: ui-node
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30002

