apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-server-deployment-green
  labels:
    app: search-server 
    kube-monkey/enabled: "enabled"
    kube-monkey/identifier: "search-server"
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
   
spec:
  replicas: 1
  selector:
   matchLabels:
    app: search-server
  template:
    metadata:
      labels:
        app: search-server
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "search-server"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
        color: green
    spec:
      containers:
      - name: search-server
        image: varunmachingal92/java-node:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9200

