apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-server-deployment
  labels:
   app: search-server        
spec:
  replicas: 1
  selector:
   matchLabels:
    app: search-server        
  template:
    metadata:
      labels:
        app: search-server
    spec:
      containers:
      - name: search-server
        image: varunmachingal92/java-node:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
---
kind: Service
apiVersion: v1
metadata:
  name: search-server
spec:
  type: NodePort
  selector:
   app: search-server
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30025

