# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonService', '0006_auto_20190206_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_carrier', models.TextField()),
                ('flight_carrier', models.TextField()),
                ('total_price', models.FloatField()),
                ('car_source', models.TextField()),
                ('car_destination', models.TextField()),
                ('flight_source', models.TextField()),
                ('flight_destination', models.TextField()),
                ('date', models.TextField()),
                ('search_id', models.TextField()),
                ('car_source_price', models.FloatField()),
                ('car_destination_price', models.FloatField()),
            ],
            options={
                'db_table': 'search_details',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='airportindex',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usertravel',
            options={'managed': False},
        ),
    ]
